### ISSUE TITLE
Consul registry url converter not right.

### ISSUE THREAD

**Issue by JervyShi** [alipay/sofa-rpc#449]
### Describe the bug

`ConsulURL#valueOf` can not return right url instance.

### Expected behavior

Input: `bolt://127.0.0.1:12200?accepts=100000&appName=samples&delay=-1&dynamic=true&id=helloFutureServiceImpl&interface=com.alipay.sofa.rpc.samples.invoke.HelloFutureService&language=java&pid=16262&protocol=bolt&rpcVer=50500&serialization=hessian2&startTime=1545361899136&timeout=0&uniqueId=&version=1.0&weight=100`

Output: 
```
ConsulURL:
    protocol: bolt
    host: 127.0.0.1
    port: 12200
    interface: com.alipay.sofa.rpc.samples.invoke.HelloFutureService
    parameters: map...
``` 

### Actual behavior

Output:  `ConsulURL.interface` is null.

### Environment

- SOFARPC version: 5.5.0-SNAPSHOT
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`):
- Maven version: 3.2.5
- IDE version:
